### PR TITLE
Created Navbar

### PR DESCRIPTION
**Pull request by vansh-attri**
Created Navbar. Solved Issue #6 
Screenshot 2023-10-13 202126

### CODE REVIEW

**Comment by ACM-CIET** [comment]
@vansh-attri great work just please resolve conflicts in contributors/main.json and sync your fork

**Comment by vansh-attri** [comment]
Sure. Will do.

**Comment by vansh-attri** [comment]
Done. Please Check.

**Comment by ACM-CIET** [comment]
Great work @vansh-attri  don’t forget to star the repo! 

Happy Hacking 😄

**Pull request merged**
